version: "3.8"

services:

  nextjs:
    container_name: nextjs # container name 정의하지 않으면, 기본값이 정의됨
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Seoul

