# Use the official Nginx base image
FROM nginx

# COPY ./default.conf /etc/nginx/conf.d/default.conf

# Copy custom configuration file to Nginx's default configuration directory
COPY ./nginx.conf /etc/nginx/nginx.conf